# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_studentapplying'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplying',
            name='college',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentapplying',
            name='identity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentapplying',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentapplying',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplying',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplying',
            name='first',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplying',
            name='last',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplying',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
