# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_auto_20191107_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessEntApplying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_founder', models.CharField(max_length=20, null=True)),
                ('business_name', models.CharField(max_length=20, null=True)),
                ('business_location', models.CharField(max_length=20, null=True)),
                ('business_email', models.EmailField(max_length=254, null=True)),
                ('business_number', models.IntegerField(null=True)),
                ('business_type', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(max_length=20, null=True)),
                ('other', models.TextField(max_length=20, null=True)),
            ],
        ),
    ]
